When building Open64 on RHEL 6.0 and building a program with libhugetlbfs, a runtime link error occurs:
opencc hugebss.c -HP:bdt=2m:heap=2m 
/local/home/dgilmore/sot-pp1/bd3410/local//lib/gcc-lib/x86_64-open64-linux/4.2/libhugetlbfs_open64.so: undefined reference to `S_ISDIR'
collect2: ld returned 1 exit status
$

Apply fix from the main libhugetlbfs repository:

    $ git show 6fa46b78
    commit 6fa46b789f5f423a1d919e45306ff9357beb7898
    Author: Anton Arapov <aarapov@redhat.com>
    Date:   Mon Feb 8 14:53:43 2010 +0100

	elflink: include header, so it'll build flawlessly.

	SSIA

	Signed-off-by: Anton Arapov <aarapov@redhat.com>
	Signed-off-by: Eric B Munson <ebmunson@us.ibm.com>
     ...

Approved by Suneel.


git-svn-id: http://svn.open64.net/svnroot/open64/trunk@3445 ead328b1-e903-0410-a19d-eacee4b031f6